//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alhanoon.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlhanoonEntities : DbContext
    {
        public AlhanoonEntities()
            : base("name=AlhanoonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<About> Abouts { get; set; }
        public DbSet<Banner> Banners { get; set; }
        public DbSet<Contact> Contacts { get; set; }
        public DbSet<Cost_Comparison> Cost_Comparison { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Doctor> Doctors { get; set; }
        public DbSet<Home> Homes { get; set; }
        public DbSet<Hospital> Hospitals { get; set; }
        public DbSet<ScheduleTrip> ScheduleTrips { get; set; }
        public DbSet<Service> Services { get; set; }
        public DbSet<Treatment> Treatments { get; set; }
        public DbSet<Cost_ComparisionContent> Cost_ComparisionContents { get; set; }
        public DbSet<LatestNew> LatestNews { get; set; }
        public DbSet<Subscriber> Subscribers { get; set; }
        public DbSet<Administrator> Administrators { get; set; }
        public DbSet<Testimonial> Testimonials { get; set; }
    }
}
