//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alhanoon.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string ContactPerson_1 { get; set; }
        public string ContactPerson_2 { get; set; }
        public string MailFrom { get; set; }
        public string MailTo { get; set; }
        public string SmtpClient { get; set; }
        public int Port { get; set; }
        public string smtp_Email { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
    }
}
