//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alhanoon.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Comparison
    {
        public int Id { get; set; }
        public string Procedures { get; set; }
        public decimal US { get; set; }
        public decimal UK { get; set; }
        public decimal Bangkok { get; set; }
        public decimal India { get; set; }
        public decimal Singapore { get; set; }
        public bool IsActive { get; set; }
    }
}
